### ISSUE TITLE
Easteregg

### ISSUE THREAD

**Issue by Dani01UNIPlovdiv** [tera-private-mods/shinra-toolbox#1]
You now get rickrolled when you try to autoupdate the app. :)

**Comment by justkeepquiet** [comment]
If you have problems auto updating, it is recommended to completely uninstall the application and reinstall it.
If that doesn't help, you can install the app from this repository: https://github.com/Foglio1024/shinra-toolbox-release

Recently, there have been problems with the github servers, due to which some of the files may contain old data.
Detailed discussion here: https://github.com/orgs/community/discussions/46691

Also, please note that the latest versions of the application require .NET 7.0 to be installed.
